version: '3.8'

services:
  database:
    image: postgres:16
    environment:
      POSTGRES_USER: dev_team
      POSTGRES_PASSWORD: marmotte
      POSTGRES_DB: trip_share_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5454:5432"

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://dev_team:marmotte@database:5432/trip_share_db"
    depends_on:
      - database
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    command: >
      sh -c "php -S 0.0.0.0:8000 -t public"

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    command: ["npm", "run", "serve"]

volumes:
  postgres_data:
